// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package cmd

import (
	"github.com/gin-gonic/gin"
)

// InitializeApp constructs the application using the manually wired function.
// This file simulates the code that would be generated by running `wire`.
func InitializeApp() (*gin.Engine, error) {
	return initializeAppManual()
}
